/* ============================================================
   Pre-built Search Index — The Business Lab Training Portal
   Each entry: { url, title, module, keywords[], excerpt }
   ============================================================ */

const SEARCH_INDEX = [
  // ── Module 1: Getting Started ──
  { url: 'getting-started/index.html', title: 'Getting Started Overview', module: 'Getting Started', keywords: ['start', 'begin', 'introduction', 'welcome', 'onboarding'], excerpt: 'Welcome to The Business Lab platform. This module covers everything you need to get up and running with the system.' },
  { url: 'getting-started/logging-in.html', title: 'Logging In', module: 'Getting Started', keywords: ['login', 'password', 'credentials', 'sign in', 'authentication', 'access', 'email'], excerpt: 'Learn how to access the staff portal, reset your password, and troubleshoot common login issues.' },
  { url: 'getting-started/staff-portal-layout.html', title: 'Staff Portal Layout', module: 'Getting Started', keywords: ['portal', 'dashboard', 'navigation', 'layout', 'menu', 'interface', 'sidebar'], excerpt: 'Understand the staff portal layout including the sidebar navigation, quick action buttons, and dashboard widgets.' },
  { url: 'getting-started/profile-setup.html', title: 'Profile Setup', module: 'Getting Started', keywords: ['profile', 'account', 'settings', 'name', 'photo', 'preferences'], excerpt: 'Set up your staff profile including display name, profile photo, notification preferences, and default location.' },
  { url: 'getting-started/location-management.html', title: 'Location Management', module: 'Getting Started', keywords: ['location', 'branch', 'site', 'switch', 'multi-location', 'filter'], excerpt: 'Learn how to switch between business locations and understand location-based data filtering.' },

  // ── Module 2: Client Database ──
  { url: 'client-database/index.html', title: 'Client Database Overview', module: 'Client Database', keywords: ['client', 'database', 'patient', 'record', 'CRM'], excerpt: 'The Master Client Database is the central hub for all client information across your business.' },
  { url: 'client-database/overview.html', title: 'Database Overview', module: 'Client Database', keywords: ['database', 'layout', 'columns', 'table', 'records', 'interface'], excerpt: 'Tour the client database interface, including the data table, column controls, and summary statistics.' },
  { url: 'client-database/searching.html', title: 'Searching for Clients', module: 'Client Database', keywords: ['search', 'find', 'filter', 'lookup', 'query', 'name', 'phone', 'email'], excerpt: 'Find clients quickly using search, filters, and advanced query options across all fields.' },
  { url: 'client-database/adding-clients.html', title: 'Adding New Clients', module: 'Client Database', keywords: ['add', 'new', 'create', 'register', 'client ID', 'BL-', 'intake'], excerpt: 'Register new clients with auto-generated client IDs, required fields, and optional demographic data.' },
  { url: 'client-database/editing-clients.html', title: 'Editing Client Records', module: 'Client Database', keywords: ['edit', 'update', 'modify', 'change', 'record', 'field'], excerpt: 'Update client information including contact details, addresses, and custom fields with full edit history.' },
  { url: 'client-database/client-status.html', title: 'Client Status & Tags', module: 'Client Database', keywords: ['status', 'active', 'inactive', 'tags', 'labels', 'categorize'], excerpt: 'Manage client status (Active, Inactive, VIP) and use tags to categorize and segment your client base.' },
  { url: 'client-database/trash-system.html', title: 'Trash & Recovery', module: 'Client Database', keywords: ['trash', 'delete', 'recover', 'restore', 'archive', 'undo'], excerpt: 'Safely delete client records to the trash bin with the ability to recover them within 30 days.' },
  { url: 'client-database/exporting.html', title: 'Exporting Data', module: 'Client Database', keywords: ['export', 'CSV', 'download', 'spreadsheet', 'report', 'data'], excerpt: 'Export client data to CSV files for reporting, mail merges, or backup purposes.' },
  { url: 'client-database/family-relationships.html', title: 'Family Relationships', module: 'Client Database', keywords: ['family', 'relationship', 'household', 'spouse', 'parent', 'child', 'link'], excerpt: 'Link clients as family members to manage household accounts and shared billing.' },

  // ── Module 3: Billing & Payments ──
  { url: 'billing/index.html', title: 'Billing & Payments Overview', module: 'Billing & Payments', keywords: ['billing', 'payment', 'charge', 'invoice', 'money'], excerpt: 'The billing system handles all financial transactions including card payments, cash, invoicing, and statements.' },
  { url: 'billing/overview.html', title: 'Billing Overview', module: 'Billing & Payments', keywords: ['billing', 'tab', 'balance', 'charges', 'payments', 'interface'], excerpt: 'Understand the billing interface, client balance display, and the relationship between charges and payments.' },
  { url: 'billing/card-payments.html', title: 'Card Payments', module: 'Billing & Payments', keywords: ['card', 'credit', 'debit', 'Stripe', 'charge', 'swipe', 'tap'], excerpt: 'Process credit and debit card payments through the integrated Stripe payment system.' },
  { url: 'billing/cash-check-payments.html', title: 'Cash & Check Payments', module: 'Billing & Payments', keywords: ['cash', 'check', 'manual', 'payment', 'record'], excerpt: 'Record cash and check payments manually with proper documentation and receipt generation.' },
  { url: 'billing/quick-purchase.html', title: 'Quick Purchase', module: 'Billing & Payments', keywords: ['quick', 'purchase', 'one-click', 'fast', 'simple', 'charge'], excerpt: 'Use Quick Purchase for fast, simple transactions when a full invoice is not needed.' },
  { url: 'billing/saved-cards.html', title: 'Saved Cards', module: 'Billing & Payments', keywords: ['saved', 'card', 'stored', 'file', 'recurring', 'token'], excerpt: 'Manage saved payment cards on file for recurring charges and faster checkout.' },
  { url: 'billing/billing-statements.html', title: 'Billing Statements', module: 'Billing & Payments', keywords: ['statement', 'invoice', 'bill', 'summary', 'email', 'print'], excerpt: 'Generate and send billing statements to clients showing charges, payments, and balances.' },
  { url: 'billing/writeoffs-adjustments.html', title: 'Write-offs & Adjustments', module: 'Billing & Payments', keywords: ['writeoff', 'adjustment', 'discount', 'credit', 'correction', 'waive'], excerpt: 'Apply write-offs, credits, and balance adjustments for billing corrections and courtesy discounts.' },
  { url: 'billing/receipts.html', title: 'Receipts', module: 'Billing & Payments', keywords: ['receipt', 'print', 'email', 'confirmation', 'transaction'], excerpt: 'Generate, print, and email payment receipts for completed transactions.' },
  { url: 'billing/payment-history.html', title: 'Payment History', module: 'Billing & Payments', keywords: ['history', 'log', 'transactions', 'audit', 'past', 'record'], excerpt: 'View complete payment history for any client with filtering, date ranges, and audit trail.' },

  // ── Module 4: Front Desk ──
  { url: 'front-desk/index.html', title: 'Front Desk Overview', module: 'Front Desk Operations', keywords: ['front desk', 'reception', 'operations', 'daily'], excerpt: 'The front desk dashboard is your command center for daily operations, check-ins, and client management.' },
  { url: 'front-desk/dashboard.html', title: 'Front Desk Dashboard', module: 'Front Desk Operations', keywords: ['dashboard', 'widgets', 'stats', 'today', 'overview'], excerpt: 'Navigate the front desk dashboard including today\'s appointments, check-in queue, and quick stats.' },
  { url: 'front-desk/check-in.html', title: 'Client Check-In', module: 'Front Desk Operations', keywords: ['check-in', 'arrival', 'kiosk', 'sign in', 'queue'], excerpt: 'Process client check-ins using the kiosk system or manual check-in from the front desk.' },
  { url: 'front-desk/walk-ins.html', title: 'Handling Walk-Ins', module: 'Front Desk Operations', keywords: ['walk-in', 'no appointment', 'new client', 'drop-in', 'availability'], excerpt: 'Handle walk-in clients who arrive without appointments, including quick registration and availability checks.' },
  { url: 'front-desk/task-management.html', title: 'Task Management', module: 'Front Desk Operations', keywords: ['task', 'todo', 'assign', 'reminder', 'follow-up', 'checklist'], excerpt: 'Create, assign, and track tasks for your team including follow-ups, reminders, and daily checklists.' },
  { url: 'front-desk/end-of-day.html', title: 'End of Day Procedures', module: 'Front Desk Operations', keywords: ['end of day', 'close', 'closing', 'reconcile', 'EOD', 'wrap-up'], excerpt: 'Complete end-of-day procedures including cash reconciliation, report review, and system close-out.' },

  // ── Module 5: POS ──
  { url: 'pos/index.html', title: 'Point of Sale Overview', module: 'Point of Sale', keywords: ['POS', 'point of sale', 'register', 'terminal', 'sales'], excerpt: 'The Point of Sale system handles retail transactions, product sales, and in-person payment processing.' },
  { url: 'pos/terminal-overview.html', title: 'Terminal Overview', module: 'Point of Sale', keywords: ['terminal', 'screen', 'layout', 'POS interface', 'register'], excerpt: 'Learn the POS terminal layout including product grid, cart, payment area, and function keys.' },
  { url: 'pos/processing-sales.html', title: 'Processing Sales', module: 'Point of Sale', keywords: ['sale', 'transaction', 'sell', 'ring up', 'scan', 'add item'], excerpt: 'Ring up sales by adding items to the cart, applying quantities, and processing payment.' },
  { url: 'pos/discounts-promos.html', title: 'Discounts & Promotions', module: 'Point of Sale', keywords: ['discount', 'coupon', 'promo', 'promotion', 'percent off', 'sale price'], excerpt: 'Apply discounts, promotional codes, and special pricing during POS transactions.' },
  { url: 'pos/returns-refunds.html', title: 'Returns & Refunds', module: 'Point of Sale', keywords: ['return', 'refund', 'exchange', 'credit', 'void', 'cancel'], excerpt: 'Process returns, issue refunds, handle exchanges, and void incomplete transactions.' },
  { url: 'pos/cash-drawer.html', title: 'Cash Drawer Management', module: 'Point of Sale', keywords: ['cash', 'drawer', 'register', 'count', 'float', 'change'], excerpt: 'Manage the cash drawer including opening float, cash counts, and end-of-shift balancing.' },
  { url: 'pos/receipts-printing.html', title: 'Receipts & Printing', module: 'Point of Sale', keywords: ['receipt', 'print', 'printer', 'thermal', 'email receipt'], excerpt: 'Configure receipt printers, customize receipt format, and offer email receipts to clients.' },
  { url: 'pos/daily-reports.html', title: 'Daily POS Reports', module: 'Point of Sale', keywords: ['report', 'daily', 'summary', 'sales report', 'totals', 'Z report'], excerpt: 'Generate and review daily POS reports including sales totals, payment breakdowns, and item summaries.' },

  // ── Module 6: Booking ──
  { url: 'booking/index.html', title: 'Booking & Scheduling Overview', module: 'Booking & Scheduling', keywords: ['booking', 'scheduling', 'appointment', 'calendar', 'reserve'], excerpt: 'The booking system manages appointments, provider schedules, and automated client notifications.' },
  { url: 'booking/calendar-overview.html', title: 'Calendar Overview', module: 'Booking & Scheduling', keywords: ['calendar', 'view', 'day', 'week', 'month', 'schedule'], excerpt: 'Navigate the booking calendar with day, week, and month views, color-coded by provider or service.' },
  { url: 'booking/creating-bookings.html', title: 'Creating Bookings', module: 'Booking & Scheduling', keywords: ['create', 'new', 'book', 'appointment', 'schedule', 'reserve'], excerpt: 'Create new bookings by selecting a client, service, provider, and available time slot.' },
  { url: 'booking/managing-bookings.html', title: 'Managing Bookings', module: 'Booking & Scheduling', keywords: ['manage', 'edit', 'cancel', 'reschedule', 'move', 'no-show'], excerpt: 'Edit, reschedule, or cancel existing bookings, and mark clients as no-shows.' },
  { url: 'booking/provider-schedules.html', title: 'Provider Schedules', module: 'Booking & Scheduling', keywords: ['provider', 'schedule', 'availability', 'hours', 'time off', 'block'], excerpt: 'Set up provider availability, working hours, time-off blocks, and recurring schedule patterns.' },
  { url: 'booking/notifications.html', title: 'Booking Notifications', module: 'Booking & Scheduling', keywords: ['notification', 'reminder', 'email', 'SMS', 'confirmation', 'alert'], excerpt: 'Configure automated booking confirmations, reminders, and cancellation notifications.' },

  // ── Module 7: Menu & Catalog ──
  { url: 'menu-management/index.html', title: 'Menu & Catalog Overview', module: 'Menu & Catalog', keywords: ['menu', 'catalog', 'products', 'services', 'items'], excerpt: 'Manage your product and service catalog including items, categories, pricing, and inventory.' },
  { url: 'menu-management/catalog-overview.html', title: 'Catalog Overview', module: 'Menu & Catalog', keywords: ['catalog', 'list', 'browse', 'items', 'products', 'services'], excerpt: 'Tour the catalog management interface and understand how items are organized and displayed.' },
  { url: 'menu-management/adding-items.html', title: 'Adding Items', module: 'Menu & Catalog', keywords: ['add', 'create', 'new item', 'product', 'service', 'listing'], excerpt: 'Add new products or services to your catalog with descriptions, images, and pricing.' },
  { url: 'menu-management/categories.html', title: 'Categories & Organization', module: 'Menu & Catalog', keywords: ['category', 'organize', 'group', 'sort', 'folder', 'section'], excerpt: 'Create and manage categories to keep your catalog organized and easy to navigate.' },
  { url: 'menu-management/pricing.html', title: 'Pricing & Variants', module: 'Menu & Catalog', keywords: ['price', 'pricing', 'variant', 'size', 'option', 'cost', 'markup'], excerpt: 'Set up pricing including variants (sizes, options), cost tracking, and markup calculations.' },
  { url: 'menu-management/inventory.html', title: 'Inventory Tracking', module: 'Menu & Catalog', keywords: ['inventory', 'stock', 'quantity', 'low stock', 'reorder', 'count'], excerpt: 'Track inventory levels, set low-stock alerts, and manage reorder points for physical products.' },

  // ── Module 8: Accounting ──
  { url: 'accounting/index.html', title: 'Accounting & Reports Overview', module: 'Accounting & Reports', keywords: ['accounting', 'reports', 'analytics', 'finance', 'numbers'], excerpt: 'Access financial reports, analytics dashboards, and accounting tools for business insights.' },
  { url: 'accounting/dashboard.html', title: 'Analytics Dashboard', module: 'Accounting & Reports', keywords: ['analytics', 'dashboard', 'charts', 'graphs', 'metrics', 'KPI'], excerpt: 'Use the analytics dashboard to view real-time business metrics, trends, and key performance indicators.' },
  { url: 'accounting/revenue-reports.html', title: 'Revenue Reports', module: 'Accounting & Reports', keywords: ['revenue', 'income', 'sales', 'earnings', 'top-line'], excerpt: 'Generate revenue reports by date range, service type, provider, and location.' },
  { url: 'accounting/payment-reports.html', title: 'Payment Reports', module: 'Accounting & Reports', keywords: ['payment', 'report', 'transaction', 'method', 'breakdown'], excerpt: 'View payment reports broken down by payment method, status, and date range.' },
  { url: 'accounting/export-reports.html', title: 'Exporting Reports', module: 'Accounting & Reports', keywords: ['export', 'download', 'CSV', 'PDF', 'print', 'email report'], excerpt: 'Export reports as CSV or PDF files, and email reports directly to stakeholders.' },
  { url: 'accounting/reconciliation.html', title: 'Reconciliation', module: 'Accounting & Reports', keywords: ['reconcile', 'reconciliation', 'match', 'bank', 'verify', 'balance'], excerpt: 'Reconcile system records with bank statements and Stripe payouts to ensure accuracy.' },

  // ── Module 9: Staff Management ──
  { url: 'staff-management/index.html', title: 'Staff Management Overview', module: 'Staff Management', keywords: ['staff', 'team', 'employee', 'management', 'HR'], excerpt: 'Manage your team including adding staff, setting permissions, and tracking performance.' },
  { url: 'staff-management/adding-staff.html', title: 'Adding Staff Members', module: 'Staff Management', keywords: ['add', 'new staff', 'employee', 'invite', 'onboard', 'hire'], excerpt: 'Add new staff members to the system with login credentials, roles, and location assignments.' },
  { url: 'staff-management/roles.html', title: 'Roles & Permissions', module: 'Staff Management', keywords: ['role', 'permission', 'access', 'admin', 'manager', 'staff', 'security'], excerpt: 'Configure role-based access control to restrict system features based on staff roles.' },
  { url: 'staff-management/performance.html', title: 'Performance Tracking', module: 'Staff Management', keywords: ['performance', 'tracking', 'metrics', 'goals', 'review', 'productivity'], excerpt: 'Track staff performance metrics including client interactions, tasks completed, and revenue generated.' },

  // ── Module 10: Advanced ──
  { url: 'advanced/index.html', title: 'Advanced Features Overview', module: 'Advanced Features', keywords: ['advanced', 'features', 'power user', 'expert'], excerpt: 'Explore advanced platform features including email marketing, activity logs, and integrations.' },
  { url: 'advanced/email-marketing.html', title: 'Email Marketing', module: 'Advanced Features', keywords: ['email', 'marketing', 'campaign', 'newsletter', 'broadcast', 'template'], excerpt: 'Create and send email marketing campaigns to your client base with templates and segmentation.' },
  { url: 'advanced/activity-logs.html', title: 'Activity Logs', module: 'Advanced Features', keywords: ['activity', 'log', 'audit', 'history', 'tracking', 'who did what'], excerpt: 'Review the activity log to see all system actions including who did what and when.' },
  { url: 'advanced/data-backups.html', title: 'Data & Backups', module: 'Advanced Features', keywords: ['backup', 'data', 'export', 'restore', 'safety', 'recovery'], excerpt: 'Understand data backup procedures, export options, and disaster recovery processes.' },
  { url: 'advanced/integrations.html', title: 'Integrations', module: 'Advanced Features', keywords: ['integration', 'API', 'connect', 'third-party', 'Stripe', 'webhook'], excerpt: 'Connect with third-party services including payment processors, email providers, and custom APIs.' }
];
